### ISSUE TITLE
New timer feature?

### ISSUE THREAD

**Issue by brennv** [kaushik94/Alex#1]
Thanks for sharing Alex! It's been really helpful. What do you think if we added a small timer to give folks a better idea if their code might time out on some of the bots? We could use a decorator to kick out rough run times of each pass of do_it and _test_python_normal.

**Comment by kaushik94** [comment]
@brennan-v-  thanks for taking interest and I'm glad its helpful. This sounds like a good idea, we could output on the right side for every test case its run-time. Would you like to make a PR or should I ? And I also see you have fixed some indentation issues !

**Comment by brennv** [comment]
I'll submit the pull request and see what you think. I like the idea of printing the results at the end, but right now it looks like this.
![timer_test](https://cloud.githubusercontent.com/assets/10409276/7594282/8c77e7b4-f8ad-11e4-874d-731246f6292d.JPG)

**Comment by kaushik94** [comment]
It would be better if we could do something like:

```
TESTCASE 1 FAIL 0.041 seconds
TESTCASE 2 FAIL 0.035 seconds
```

**Comment by brennv** [comment]
Cool, fixed it. Yes, that looks better.

**Comment by kaushik94** [comment]
Good !

**Comment by kaushik94** [comment]
Also please add a star if you appreciate it !

**Comment by brennv** [comment]
Starred it!

**Comment by kaushik94** [comment]
Hey @brennan-v-  please add yourself to authors also. I don't know your details.
